@startuml sekolah
entity aktifasi{
    *id : INT (PK)
    --
    kode_aktifasi : INT
    status : VARCHAR
}
entity role{
    *id : INT (PK)
    --
    kode_role : INT
    status : VARCHAR
}
entity user{
    *id : INT (PK)
    --
    *id_role : INT (FK)
    *id_aktifasi : INT (FK)
    nama : VARCHAR
    password : VARCHAR
}
entity siswa{
    *id : INT (PK)
    --
    *id_user : INT (FK)
    *id_kelas : INT (FK)
    *id_agama : INT (FK)
    nis : INT
    NISN : INT
    Jenis Kelamin : INT
}

entity guru{
    *id : INT (PK)
    --
    id_user : INT (FK)
    nip : INT
}
entity mapel{
    *id : INT (PK)
    --
    id_kelas : INT (FK)
    id_guru : INT (FK)
    id_pelajaran : INT (FK)
}
entity kelas{
    *id : INT (PK)
    --
    nama_kelas : VARCHAR
}
entity jadwal{
    *id : INT (PK)
    --
    id_kelas : INT (FK)
    id_guru : INT (FK)
    id_pelajaran : INT (FK)
    id_hari : INT (FK)
}
entity jurusan{
    *id INT (PK)
    --
}

entity pelajaran{
    *id INT (PK)
    --
    nama_pelajaran : VARCHAR
}
entity hari{
    *id : INT (PK)
    --
    hari : (VARCHAR)
}

entity tipenilai{
    *id : INT (PK)
    --
    kode_tipenilai : INT
    nama_nilai : VARCHAR
}

entity nilai{
    *id : INT (PK)
    --
    id_siswa : INT (FK)
    id_guru : INT (FK)
    id_pelajaran : INT (FK)
    id_tipenilai : INT (FK)
    total_nilai : INT

}entity agama{
    *id : INT (PK)
    --
    kode_agama : INT
    nama_agama : VARCHAR
}
@enduml