# Generated by Django 4.0.5 on 2022-06-19 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guru',
            name='nama_guru',
        ),
        migrations.CreateModel(
            name='mapel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_guru', models.ForeignKey(db_column='id_guru', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.guru')),
                ('id_pelajaran', models.ForeignKey(db_column='id_pelajaran', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.pelajaran')),
            ],
            options={
                'verbose_name_plural': 'mapel',
                'db_table': 'mapel',
            },
        ),
    ]
